FROM node:17

# Create app directory
WORKDIR /app

COPY . .

RUN npm i -g npm@latest; \
    # Install & Setup pnpm
    npm install -g pnpm; \
    pnpm --version; \
    pnpm setup; \
    mkdir -p /usr/local/share/pnpm &&\
    export PNPM_HOME="/usr/local/share/pnpm" &&\
    export PATH="$PNPM_HOME:$PATH"; \
    pnpm bin -g

# Install deps
RUN pnpm install

ENTRYPOINT [ "pnpm", "run", "start:debug" ]

