FROM node:16 AS builder

# Create app directory
WORKDIR /app

COPY . .

# Install app dependencies
RUN npm i -g npm@latest; \
    # Install pnpm
    npm install -g pnpm; \
    pnpm --version; \
    pnpm setup; \
    mkdir -p /usr/local/share/pnpm &&\
    export PNPM_HOME="/usr/local/share/pnpm" &&\
    export PATH="$PNPM_HOME:$PATH"; \
    pnpm bin -g &&\
    # Install dependencies
    pnpm install


ENTRYPOINT [ "npm", "run", "start:debug" ]

